---
title: "Interactive Hydrology Lessons for WR696"
author: 
date: 
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---
# R intro

 - [Introductory R markdown](hydrology/R_intro/src/R_intro_696.html)

# Hydrology labs and assignments

### Meteorological Measurements 

  - [Meteorological Measurements lecture and text](hydrology/5_met_lab/5_met_lab.html)
  
### Hydrographs & Rating Curves 

  - [Hydrographs & Rating Curves lecture and text](hydrology/7_rating_curve/7_rating_curve.html)


### Velocity Area 
  
  - [Velocity Area lecture and text](hydrology/2_velocity_area_module/2_velocity_area_module.html)
  
  - Rubric [here](hydrology/2_velocity_area_module/2_velocity_area_module_files/velocity_area_rubric.pdf)
  
  - Analysis assessment [here](https://www.dropbox.com/s/pp7spwyk9maa4ul/Velo_Area_Assessment.xlsx?dl=0)
  
### Udall Natural Area
  - [Udall assignment](hydrology/Udall_Natural_Area/Udall.html)
  
### Groundwater
  
  - [Groundwater lecture and text](hydrology/Groundwater/Groundwater.html)
  
### Fluvial Geomorphology 

  - [Fluvial Geomorphology lecture and text](hydrology/6_geomorph/6_geomorph.html)
  
  - Rubric [here](hydrology/6_geomorph/6_geomorph_files/geomorph_rubric.pdf)
  
  - Analysis assessment [here](https://www.dropbox.com/s/x5ullpuu2lu33yd/Mannings_Assessment.xlsx?dl=0)
  
###  Stream Health 

  - [Stream Health lecture and text](hydrology/4_stream_health/4_stream_health.html)
  
  - Analysis assessment [here](https://www.dropbox.com/s/9cmi8a1w448q41e/Stream_Health_Assesment.pdf?dl=0)

### Dilution Gauging 

  - [Dilution Gauging lecture and text](hydrology/3_dilution_gauging/3_dilution_gauging.html)
  
  - Rubric [here](hydrology/3_dilution_gauging/3_dilution_gauging_files/dilution_gauging_rubric.pdf)
  
  - Analysis assessment [here](https://www.dropbox.com/s/hkpucfp1g7lhlj3/DG_Assessment.xlsx?dl=0)
  

### Hydrograph Separation 

  - [Baseflow and Stormflow lecture and text](hydrology/1_baseflow_stormflow/0_hydrograph_separation_lecture.html)

  - Rubric [here](hydrology/1_baseflow_stormflow/Hydrolearn_OUtline_Baseflow.pdf)
  
  - Analysis assessment [here](https://cuahsi.shinyapps.io/1_baseflow_vs_stormflow/)
  
  - Interactive web app on mountaintop mining impacts to streamflow [here](https://cuahsi.shinyapps.io/mtm_baseflow/)
  


## Stand alone shiny apps

These applications have no teaching material associated with them, but could
be easily included into class exercises or homeworks. 

- [Colorado Streamflow and Watershed Attributes (Stephanie Kampf)](https://cuahsi.shinyapps.io/CO_streamflow/)

- [Hubbard Brook Experimental Forest Discharge by JP Gannon](https://cuahsi.shinyapps.io/HBEF_Discharge/)

- [Joyful Q by Lauren Steely](https://lsteely.shinyapps.io/streamflow_joyplots/)

<br> 
<br> 

# Biogeochemistry tools

## Stand Alone shiny applications

- [Water quality change in blue river watershed, CO](https://cuahsi.shinyapps.io/blue_watershed/)

- [Weathering impacts from mountaintop mining](https://cuahsi.shinyapps.io/mtm_weathering/)

- [National water quality inventories and data](http://waterqualityexplorer.rc.duke.edu:3838/explorer/)

## Stand Alone Assignments (interactive tutorials)

- [Working with the WQP](https://cuahsi.shinyapps.io/Public_WQ_Data/)

