---
title: "Online learning"
author: "Tim Covino"
date: "9/8/2021"
output:
html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

# Contributions to teaching

The department currently has 3 online courses that form the [Water Resources Graduate Certificate](https://www.online.colostate.edu/certificates/water-resources/). These courses are currently taught by adjunct instructors. I suggest that having a regular faculty member teach 2-3 of these courses would be benefificial for a variety of reasons. First, it would provide longer-term stability for the courses in terms of identifying a consistent instructor from year to year. Second, it would provide cost savings to the department. Third, it would allow PSM and other graduate students to interact with a regular faculty member who would like to lead the PSM in water (more about this later). 
<br>

The courses reqired for the certificate are:

  * [WR511 Water Resource Development](https://www.online.colostate.edu/courses/WR/WR511.dot). This class is similar to the "Water in the West" we have discussed and could be developed into that.
  <br>
  * [WR512 Water Law for Non-Lawyers](https://www.online.colostate.edu/courses/WR/WR512.dot). This class would be furthest from my central expertise but is an area I've wanted to explore for some time. 
  <br>
  * [WR514 GIS and Data Analysis in Water Resources](https://www.online.colostate.edu/courses/WR/WR514.dot). This is my central expertise and central to my research program. I would develop this into an R based course as we are using R to teach our classes in both the PSM and undergraduate Watershed degrees. 
<br>

I could teach 2 or 3 of the classes listed above. I could see rotating on 512 with the new instructor if that person has capacity.
<br>

I also suggest that having a person in the department working on developing our online capacity is beneficial to the department and also helps broaden access. From [Inside Higher Ed](https://www.insidehighered.com/quicktakes/2021/02/08/demand-graduate-school-rises-even-greater-competition-looms):
<br>

*“The share of graduate students as part of overall enrollment has grown over the last decade,” Dan | Fiori, associate analyst at Moody’s, said in a press release. “Universities are poised to bolster enrollment through online programs that expand reach while demand for more traditional degrees will remain strong with demonstrated benefits in employment opportunities. As online learning grows into a more respected educational platform, it has garnered increasing graduate student demand regardless of institution type.”*
<br>

And I have been very interested in leading this effort since the inception of the PSM in water. In fact, I would like to work toward developing a fully online version of the PSM in water. 

# Service

Largely, I feel that much of my service would remain the same. However, what I would like to focus my service on are two-fold:
<br>

* First is leading and growing the PSM. The growth aspect depends on what we want as a final number. We have discussed that 200 students is not what we want. Regardless, I'd like to continue to lead the water aspect of this program, and work to grow and improve it.
<br>

* Second is online learning. I would like to work to grow the online capacity in both graduate level and undergraduate level courses. In particular, I would like to focus on developing a fully online version of the PSM. I think that the increased access to higher education that provides is really important and a core value of the land grant mission. Similarly, there are some undergraduate level courses that would be appropriate for an online version (hybrid?) as well. 
<br>

My service to the hydrological commnunity beyond CSU would remain unchanged. 


# Research

My research program remains unchanged. 









